Fri Oct 22 10:53:26 PDT 1999 (Mandrake)
removed almost all the warnings.
except for:
main.c:287: warning: implicit declaration of function `__imlib_draw_line'
which I believe is because it's not using the appropriate API call yet.


SVN revision: 945